"""
Base Strategy class for the Intraday Statistical Arbitrage System.

This module defines the base Strategy interface that all strategies must implement.
"""

import abc
from typing import Dict, List, Any, Optional

class Strategy(abc.ABC):
    """
    Base class for all trading strategies.
    
    This abstract base class defines the interface that all strategies must implement.
    """
    
    def __init__(self, name: Optional[str] = None, **kwargs):
        """
        Initialize a strategy.
        
        Parameters:
        -----------
        name : str, optional
            Human-readable name for the strategy
        **kwargs : dict
            Additional strategy-specific parameters
        """
        self.name = name or self.__class__.__name__
        self.config = kwargs
    
    @abc.abstractmethod
    def update(self, current_data: Dict[str, Any]) -> Dict[str, Any]:
        """
        Update the strategy with current market data.
        
        Parameters:
        -----------
        current_data : Dict[str, Any]
            Current market data
            
        Returns:
        --------
        Dict[str, Any]
            Dictionary containing strategy actions or signals
        """
        pass
    
    @abc.abstractmethod
    def generate_orders(self, signals: Dict[str, Any]) -> List[Dict[str, Any]]:
        """
        Convert signals into executable orders.
        
        Parameters:
        -----------
        signals : Dict[str, Any]
            Strategy signals generated by the update method
            
        Returns:
        --------
        List[Dict[str, Any]]
            List of orders to execute
        """
        pass
    
    def __str__(self) -> str:
        """Return string representation of the strategy."""
        return f"{self.name} Strategy"
    
    def __repr__(self) -> str:
        """Return detailed string representation of the strategy."""
        return f"{self.__class__.__name__}(name='{self.name}')" 