#!/usr/bin/env python3
"""
Script to generate an HTML dashboard from code metrics data.

This script reads the JSON report generated by code_metrics.py and creates
a visually appealing HTML dashboard with charts and tables.
"""

import os
import sys
import json
import argparse
import datetime
from pathlib import Path
from typing import Dict, List, Any, Optional


HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Code Quality Dashboard</title>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body {{
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            padding: 20px;
            background-color: #f5f7fa;
        }}
        .dashboard-header {{
            padding: 15px;
            margin-bottom: 20px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }}
        .metric-card {{
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
            padding: 15px;
            margin-bottom: 20px;
            transition: transform 0.2s ease;
        }}
        .metric-card:hover {{
            transform: translateY(-5px);
            box-shadow: 0 5px 15px rgba(0,0,0,0.1);
        }}
        .metric-value {{
            font-size: 2.5rem;
            font-weight: bold;
        }}
        .chart-container {{
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
            padding: 15px;
            margin-bottom: 20px;
            height: 300px;
        }}
        .table-container {{
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
            padding: 15px;
            margin-bottom: 20px;
            overflow-x: auto;
        }}
        .good {{
            color: #28a745;
        }}
        .warning {{
            color: #ffc107;
        }}
        .danger {{
            color: #dc3545;
        }}
        .badge {{
            font-size: 0.8rem;
            padding: 5px 10px;
            border-radius: 20px;
        }}
        .table-responsive {{
            overflow-x: auto;
        }}
    </style>
</head>
<body>
    <div class="container-fluid">
        <div class="dashboard-header">
            <div class="row">
                <div class="col-md-6">
                    <h1>Code Quality Dashboard</h1>
                    <p>Project: <strong>{project_name}</strong></p>
                </div>
                <div class="col-md-6 text-end">
                    <p>Generated on: <strong>{timestamp}</strong></p>
                    <p>Files analyzed: <strong>{files_analyzed}</strong></p>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-3">
                <div class="metric-card text-center">
                    <h5>Total Lines of Code</h5>
                    <div class="metric-value">{total_lines}</div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="metric-card text-center">
                    <h5>Docstring Coverage</h5>
                    <div class="metric-value {docstring_color}">{docstring_coverage}%</div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="metric-card text-center">
                    <h5>Type Hint Coverage</h5>
                    <div class="metric-value {typehint_color}">{type_hint_coverage}%</div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="metric-card text-center">
                    <h5>Duplicate Blocks</h5>
                    <div class="metric-value {duplicate_color}">{duplicate_blocks}</div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <div class="chart-container">
                    <canvas id="complexityChart"></canvas>
                </div>
            </div>
            <div class="col-md-6">
                <div class="chart-container">
                    <canvas id="lineTypesChart"></canvas>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="table-container">
                    <h4>Files with Highest Complexity</h4>
                    <div class="table-responsive">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>File</th>
                                    <th>Lines</th>
                                    <th>Max Complexity</th>
                                    <th>Avg Complexity</th>
                                    <th>Docstring</th>
                                    <th>Type Hints</th>
                                </tr>
                            </thead>
                            <tbody>
                                {complexity_table_rows}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="table-container">
                    <h4>Duplicate Code Blocks</h4>
                    <div class="table-responsive">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>Lines</th>
                                    <th>Tokens</th>
                                    <th>Occurrences</th>
                                </tr>
                            </thead>
                            <tbody>
                                {duplicate_table_rows}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        // Complexity distribution chart
        const complexityCtx = document.getElementById('complexityChart').getContext('2d');
        const complexityChart = new Chart(complexityCtx, {{
            type: 'bar',
            data: {{
                labels: {complexity_labels},
                datasets: [{{
                    label: 'Number of Files',
                    data: {complexity_data},
                    backgroundColor: [
                        'rgba(75, 192, 192, 0.6)',
                        'rgba(54, 162, 235, 0.6)',
                        'rgba(255, 206, 86, 0.6)',
                        'rgba(255, 159, 64, 0.6)',
                        'rgba(255, 99, 132, 0.6)'
                    ],
                    borderColor: [
                        'rgba(75, 192, 192, 1)',
                        'rgba(54, 162, 235, 1)',
                        'rgba(255, 206, 86, 1)',
                        'rgba(255, 159, 64, 1)',
                        'rgba(255, 99, 132, 1)'
                    ],
                    borderWidth: 1
                }}]
            }},
            options: {{
                responsive: true,
                maintainAspectRatio: false,
                plugins: {{
                    title: {{
                        display: true,
                        text: 'Cyclomatic Complexity Distribution'
                    }},
                    legend: {{
                        display: false
                    }},
                    datalabels: {{
                        color: '#fff',
                        font: {{
                            weight: 'bold'
                        }}
                    }}
                }},
                scales: {{
                    y: {{
                        beginAtZero: true,
                        title: {{
                            display: true,
                            text: 'Number of Files'
                        }}
                    }},
                    x: {{
                        title: {{
                            display: true,
                            text: 'Complexity Range'
                        }}
                    }}
                }}
            }}
        }});

        // Line types chart
        const lineTypesCtx = document.getElementById('lineTypesChart').getContext('2d');
        const lineTypesChart = new Chart(lineTypesCtx, {{
            type: 'doughnut',
            data: {{
                labels: ['Code', 'Comments', 'Docstrings', 'Blank'],
                datasets: [{{
                    data: [{code_lines}, {comment_lines}, {docstring_lines}, {blank_lines}],
                    backgroundColor: [
                        'rgba(54, 162, 235, 0.6)',
                        'rgba(75, 192, 192, 0.6)',
                        'rgba(153, 102, 255, 0.6)',
                        'rgba(201, 203, 207, 0.6)'
                    ],
                    borderColor: [
                        'rgba(54, 162, 235, 1)',
                        'rgba(75, 192, 192, 1)',
                        'rgba(153, 102, 255, 1)',
                        'rgba(201, 203, 207, 1)'
                    ],
                    borderWidth: 1
                }}]
            }},
            options: {{
                responsive: true,
                maintainAspectRatio: false,
                plugins: {{
                    title: {{
                        display: true,
                        text: 'Line Type Distribution'
                    }},
                    datalabels: {{
                        formatter: (value, ctx) => {{
                            let sum = 0;
                            let dataArr = ctx.chart.data.datasets[0].data;
                            dataArr.map(data => {{
                                sum += data;
                            }});
                            let percentage = (value*100 / sum).toFixed(1)+"%";
                            return percentage;
                        }},
                        color: '#fff',
                        font: {{
                            weight: 'bold'
                        }}
                    }}
                }}
            }}
        }});
    </script>
</body>
</html>"""


def get_complexity_distribution(file_metrics):
    """Calculate the distribution of complexity across files."""
    # Define complexity ranges
    ranges = [(0, 5), (6, 10), (11, 15), (16, 20), (21, float('inf'))]
    distribution = [0] * len(ranges)
    
    for file_metric in file_metrics:
        if 'error' in file_metric or 'complexity' not in file_metric:
            continue
            
        complexity = file_metric['complexity']['max']
        
        for i, (lower, upper) in enumerate(ranges):
            if lower <= complexity <= upper:
                distribution[i] += 1
                break
    
    labels = ["1-5", "6-10", "11-15", "16-20", "21+"]
    return labels, distribution


def get_complexity_table_rows(file_metrics, max_rows=10):
    """Generate HTML table rows for files with highest complexity."""
    # Sort files by complexity
    valid_metrics = [m for m in file_metrics if 'error' not in m and 'complexity' in m]
    sorted_metrics = sorted(valid_metrics, key=lambda x: x['complexity']['max'], reverse=True)
    
    rows = []
    for metric in sorted_metrics[:max_rows]:
        path = os.path.basename(metric['path'])
        
        lines = metric['line_counts']['total']
        max_complexity = metric['complexity']['max']
        avg_complexity = metric['complexity']['average']
        
        docstring_pct = metric['docstrings']['percentage']
        docstring_class = 'danger' if docstring_pct < 50 else ('warning' if docstring_pct < 80 else 'good')
        
        typehint_pct = metric['type_hints']['percentage']
        typehint_class = 'danger' if typehint_pct < 50 else ('warning' if typehint_pct < 80 else 'good')
        
        row = f"""
        <tr>
            <td>{path}</td>
            <td>{lines}</td>
            <td>
                <span class="{'danger' if max_complexity > 15 else ('warning' if max_complexity > 10 else 'good')}">
                    {max_complexity:.1f}
                </span>
            </td>
            <td>
                <span class="{'danger' if avg_complexity > 10 else ('warning' if avg_complexity > 7 else 'good')}">
                    {avg_complexity:.1f}
                </span>
            </td>
            <td>
                <span class="{docstring_class}">
                    {docstring_pct:.1f}%
                </span>
            </td>
            <td>
                <span class="{typehint_class}">
                    {typehint_pct:.1f}%
                </span>
            </td>
        </tr>
        """
        rows.append(row)
    
    return "\n".join(rows)


def get_duplicate_table_rows(duplicates, max_rows=10):
    """Generate HTML table rows for duplicate code blocks."""
    # Sort by number of lines
    sorted_duplicates = sorted(duplicates, key=lambda x: x['lines'], reverse=True)
    
    rows = []
    for duplicate in sorted_duplicates[:max_rows]:
        lines = duplicate['lines']
        tokens = duplicate['tokens']
        occurrences = len(duplicate['occurrences'])
        
        occurrence_list = "<ul class='list-unstyled'>"
        for i, occurrence in enumerate(duplicate['occurrences']):
            if i < 3:  # Show only first 3 occurrences
                occurrence_list += f"<li>{os.path.basename(occurrence['file'])}:{occurrence['line']}</li>"
        
        if occurrences > 3:
            occurrence_list += f"<li>... and {occurrences - 3} more</li>"
        
        occurrence_list += "</ul>"
        
        row = f"""
        <tr>
            <td>{lines}</td>
            <td>{tokens}</td>
            <td>{occurrence_list}</td>
        </tr>
        """
        rows.append(row)
    
    return "\n".join(rows)


def count_line_types(file_metrics):
    """Count different types of lines across all files."""
    code_lines = 0
    comment_lines = 0
    docstring_lines = 0
    blank_lines = 0
    
    for file_metric in file_metrics:
        if 'error' in file_metric or 'line_counts' not in file_metric:
            continue
            
        line_counts = file_metric['line_counts']
        code_lines += line_counts.get('code', 0)
        comment_lines += line_counts.get('comment', 0)
        docstring_lines += line_counts.get('docstring', 0)
        blank_lines += line_counts.get('blank', 0)
    
    return code_lines, comment_lines, docstring_lines, blank_lines


def generate_dashboard(metrics_file: str, output_file: str = None, project_name: str = None) -> str:
    """
    Generate an HTML dashboard from metrics data.
    
    Args:
        metrics_file: Path to the JSON metrics file
        output_file: Path to save the HTML dashboard (optional)
        project_name: Name of the project (optional)
        
    Returns:
        Path to the generated dashboard file
    """
    try:
        # Load metrics data
        with open(metrics_file, 'r') as f:
            metrics_data = json.load(f)
        
        # Set default project name if not provided
        if not project_name:
            project_name = os.path.basename(os.path.dirname(os.path.abspath(metrics_file)))
        
        # Extract timestamp
        timestamp = datetime.datetime.fromisoformat(metrics_data['timestamp']).strftime("%Y-%m-%d %H:%M:%S")
        
        # Extract summary metrics
        summary = metrics_data.get('summary', {})
        total_lines = summary.get('total_lines', 0)
        docstring_coverage = summary.get('docstring_coverage', 0)
        type_hint_coverage = summary.get('type_hint_coverage', 0)
        duplicate_blocks = summary.get('duplicate_blocks', 0)
        
        # Determine color classes based on metric values
        docstring_color = 'danger' if docstring_coverage < 50 else ('warning' if docstring_coverage < 80 else 'good')
        typehint_color = 'danger' if type_hint_coverage < 50 else ('warning' if type_hint_coverage < 80 else 'good')
        duplicate_color = 'good' if duplicate_blocks == 0 else ('warning' if duplicate_blocks < 10 else 'danger')
        
        # Get complexity distribution
        complexity_labels, complexity_data = get_complexity_distribution(metrics_data.get('file_metrics', []))
        
        # Get line type counts
        code_lines, comment_lines, docstring_lines, blank_lines = count_line_types(metrics_data.get('file_metrics', []))
        
        # Generate table rows
        complexity_table_rows = get_complexity_table_rows(metrics_data.get('file_metrics', []))
        duplicate_table_rows = get_duplicate_table_rows(metrics_data.get('duplicates', []))
        
        # Format the HTML template
        html_content = HTML_TEMPLATE.format(
            project_name=project_name,
            timestamp=timestamp,
            files_analyzed=metrics_data.get('files_analyzed', 0),
            total_lines=total_lines,
            docstring_coverage=round(docstring_coverage, 1),
            type_hint_coverage=round(type_hint_coverage, 1),
            duplicate_blocks=duplicate_blocks,
            docstring_color=docstring_color,
            typehint_color=typehint_color,
            duplicate_color=duplicate_color,
            complexity_labels=complexity_labels,
            complexity_data=complexity_data,
            code_lines=code_lines,
            comment_lines=comment_lines,
            docstring_lines=docstring_lines,
            blank_lines=blank_lines,
            complexity_table_rows=complexity_table_rows,
            duplicate_table_rows=duplicate_table_rows
        )
        
        # Save the HTML content
        if output_file:
            with open(output_file, 'w', encoding='utf-8') as f:
                f.write(html_content)
        else:
            # If no output file is specified, create one based on the metrics file
            output_file = os.path.splitext(metrics_file)[0] + '_dashboard.html'
            with open(output_file, 'w', encoding='utf-8') as f:
                f.write(html_content)
        
        return output_file
    
    except Exception as e:
        print(f"Error generating dashboard: {e}")
        import traceback
        traceback.print_exc()
        return None


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(description='Generate HTML dashboard from code metrics')
    parser.add_argument('--metrics', '-m', required=True, help='Path to the JSON metrics file')
    parser.add_argument('--output', '-o', help='Path to save the HTML dashboard')
    parser.add_argument('--project', '-p', help='Project name to display in the dashboard')
    
    args = parser.parse_args()
    
    print(f"Generating dashboard from {args.metrics}...")
    dashboard_file = generate_dashboard(args.metrics, args.output, args.project)
    
    if dashboard_file:
        print(f"Dashboard generated successfully: {dashboard_file}")
        return 0
    else:
        print("Failed to generate dashboard.")
        return 1


if __name__ == '__main__':
    sys.exit(main()) 